default:
  before_script:
    - docker info

build_image:
  script:
    - docker build -t vladimirkovelv/docker-react -f Dockerfile.dev .
    - docker run vladimirkovelv/docker-react npm run test -- --coverage